### ISSUE TITLE
Is this repo same as https://github.com/Moesif/openresty-plugin-moesif？

### ISSUE THREAD

**Issue by moonming** [Moesif/lua-resty-moesif#7]
hello, I want to add moesif plugin for https://github.com/apache/incubator-apisix, so I want to know which repo should I use? thx

**Comment by dgilling** [comment]
lua-resty-moesif, is the correct one. We just deprecated the other one.
I’ll make a note in GitHub repo. Much appreciated listing it.

Derric

**Comment by dgilling** [comment]
@moonming I am going to close the ticket and also remove the deprecated repo (It should not have been public). Do let me know if any questions.

The correct plugin to install (via luarocks):
`luarocks install lua-resty-moesif`
